### ISSUE TITLE
Fade in displayname and other names

### ISSUE THREAD

**Issue by MrEminent42** [Puharesource/TitleManager#14]
I would like a way to make the {DISPLAYNAME} or {PLAYER} or {STRIPPEDDISPLAYNAME} to fade in on each frame :)

**Comment by MrEminent42** [comment]
Any chance this could still be implemented?

**Comment by Puharesource** [comment]
Yes, however, it actually requires A LOT of stuff to be redone and for the past half a year, I've had a lot of work that needed to be done, which then resulted in this addition not being done.

I'll add this in the future and that's why I haven't closed this, though bare with me until I get the time to implement it :), I'm sorry for the extremely long delay.

**Comment by MrEminent42** [comment]
Oh sorry, I didn't realize that it would take so much work, that's why I 'bumped' this. Take your time, my life is busy too, I understand. 

And this isn't a very high priority request, just something I'd love to see. :)

**Comment by Puharesource** [comment]
Thanks for understanding :)

**Comment by Wundero** [comment]
What exactly needs to be done for this to work? I might have some free time in a couple of weeks so I could try to work on this.

**Comment by Puharesource** [comment]
He wants it to where he can also animate variables, e.g. something like this:

{PLAYER:0-1}
Would maybe show "P" if the name is "Puharesource"
or
{PLAYER:0-2}
To show "Pu"
or
{PLAYER:1-2}
to show "u"

**Comment by MrEminent42** [comment]
Yes, but I'd think it would be easier to just do {PLAYER:2} to show 2 letters.

**Comment by MrEminent42** [comment]
Whoops, didn't mean to close it, sorry!

**Comment by Wundero** [comment]
I added a pr to do something similar to this, where you do {var:(start number)[,(end number)]} where the start number is required and the end number is optional. Ex: {PLAYER:1} and {PLAYER:0,3}.

**Comment by MrEminent42** [comment]
Awesome :)

**Comment by Puharesource** [comment]
aa099ed1299b1e5a880e9aad4cdf2a49177168a1

I fixed the PR a bit, to make it work, so it should be ready for the next release :)

(The same commit, I also added some support for 1.7 clients when it comes to Actionbar messages, since a client of mine needed that for his server & I also made it to where the auto update checker is able to be disabled)

This will all be uploaded once everything is fully fixed (For anyone who wants this release early, feel free to compile it)

**Comment by MrEminent42** [comment]
Oh, awesome! Thanks a lot guys :)

**Comment by Puharesource** [comment]
1.5.10 has been released.
