### ISSUE TITLE
Can't Toggle scoreboard

### ISSUE THREAD

**Issue by RomanMines64** [Puharesource/TitleManager#244]
**Describe the bug**
So on my main account (the server owner) i can toggle it just fine. but I have an alt (without op) for testing purposes, can not toggle the scoreboard

**Expected behavior**
toggle scoreboard on/off

**Screenshots**
https://postimg.cc/kRFYcnyC

**Stacktrace / Error**
> [05:08:38] [Server thread/INFO]: SniperTrash64 issued server command: /tm scoreboard toggle

**Server information:**
 - TitleManager version: [2.1.5]
 - Spigot version: [Spigot 1.15]

**Additional context**

**Comment by Puharesource** [comment]
That's due to the fact that you don't have the required permissions to run the command. You will need to install a Permissions plugin on your server and give the required permission node to your default users' group. The permission node to toggle the scoreboard is `titlemanager.command.scoreboard`.

Using permission nodes is common practice and you will most likely end up with several issues with other plugins, if you don't install a permissions plugin.

Permission nodes can be found here:
https://github.com/Puharesource/TitleManager/wiki/permissions
