### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by austinpilz** [Puharesource/TitleManager#50]
Hi! I am really struggling to decipher your API with no documentation on it.

Right now I'm hooking into it using:
TitleManager tm = (TitleManager) Bukkit.getServer().getPluginManager().getPlugin("TitleManager");

but then I don't see an intuitive path for me to execute / send messages. Could you please help me out?

**Comment by Puharesource** [comment]
Here's a few links that might help you out:
https://jd.puharesource.io/titlemanager/
https://github.com/Puharesource/TitleManager/wiki/api-title
https://github.com/Puharesource/TitleManager/wiki/api-tab
https://github.com/Puharesource/TitleManager/wiki/api-actionbar
https://github.com/Puharesource/TitleManager/wiki/api-animations

**Comment by austinpilz** [comment]
Thank you, that documentation helps and perhaps I'm a bit of a noob when it comes to this, but how exactly am I referencing the API? It seems to be different that hooking into any other plugin. Could you provide the line(s) of code that allow you to access the api and send the message?

**Comment by Puharesource** [comment]
Think of it less as hooking and more like an API addition.
What actually happens is whenever TitleManager is loaded, all of it's classes are accessible through code, I'm utilizing this and OOP standards to provide several classes that that need to be instantiated by youself, rather than, what you're probably used to: `Methods from a class that has been initialized and saved in the plugins main class` or simply `A static class with static methods`

So from https://jd.puharesource.io/titlemanager/ `io.puharesource.mc.titlemanager.api` you should be able to see `TitleObject`, `TabTitleObject` & `ActionbarTitleObject` the names are fairly self explanatory, so I won't go over what each of the objects does... Though, to create a new instance, you simply use the `new` keyword followed by filling out the constructor of the class.

You should go have a look at the code snippets from the other links that I sent you earlier.
