### ISSUE TITLE
Allow for multiple welcome messages.

### ISSUE THREAD

**Issue by Solistika** [Puharesource/TitleManager#51]
This is just a friendly reminder to add multiple login messages! :)
welcome_message:
  '1':
    enabled: true
    title: 'hey, check out our forums!'
    subtitle: ''
    fadeIn: 40
    stay: 80
    fadeOut: 40
  '2':
    enabled: true
    title: 'hey player welcome back!'
    subtitle: ''
    fadeIn: 40
    stay: 80
    fadeOut: 40

**Comment by vanbrayne** [comment]
If you are ok with the same values for the timing settings, then maybe the syntax below could be an alternative?

enabled: true
title: ['hey, check out our forums!', 'hey player welcome back!']
subtitle: ['', '']
fadeIn: 40
stay: 80
fadeOut: 40

Från: Solistika [mailto:notifications@github.com]
Skickat: den 4 augusti 2015 09:11
Till: Puharesource/TitleManager <TitleManager@noreply.github.com>
Ämne: [TitleManager] Allow for multiple welcome messages. (#51)


This is just a friendly reminder to add multiple login messages! :)
welcome_message:
'1':
enabled: true
title: 'hey, check out our forums!'
subtitle: ''
fadeIn: 40
stay: 80
fadeOut: 40
'2':
enabled: true
title: 'hey player welcome back!'
subtitle: ''
fadeIn: 40
stay: 80
fadeOut: 40

**Comment by Puharesource** [comment]
Yes, I'll be doing that once I'm not as busy as I am at the moment :)

**Comment by Wundero** [comment]
If this was implemented, would the messages be randomly selected or all played? If they are all played, would there be different possible orders in which to play them as well?

**Comment by Puharesource** [comment]
I think it would be randomly picked due to the fact that if they want them to all be played, they could simply be displaying an animation.

**Comment by Wundero** [comment]
Ok, I can work on implementing that then.

**Comment by Puharesource** [comment]
Awesome ^^, thanks

**Comment by Solistika** [comment]
Yeah that'd work fine, the messages some people put in, or myself are
sometimes somewhat lengthy, but it would just make it a long line of text.
Not a big deal.
Hope to see it added soon :)

**Comment by Wundero** [comment]
I have a jerry-rigged implementation for this that might cover what you are looking for. The config would look a little like this:
welcome_message:
  enabled: true
  title:
  - 'Title one'
  - 'Title two'
  subtitle:
  - 'Subtitle one'
  - 'Subtitle two'
  fadeIn: 20
  stay: 40
  fadeOut: 20

The implementation would randomly select both a title and a subtitle, so from the above, these combinations would be made available:

Title one, subtitle one
Title two, subtitle one
Title one, subtitle two
Title two, subtitle two.

Everything will work the way it used to, other than that in the config it will be a list and that it will randomly select a title. Titles can still be animations.

I can try to make it map the titles to subtitles based on indices, so that it will always be first title > first subtitle, second title > second subtitle, and maybe add an option to enable/disable that, if that is something you would like to see.

**Comment by Solistika** [comment]
I would like to see first title > first subtitle, and second title > second
subtitle.

The way you mentioned would potentially work, if the messages were worded
carefully.

However if this was to become a release version, I could see some
difficulty in setup for a lot of people.

I'm just trying to think of other people who may try to setup something
similar, unless you planned on making an off-branch build just for me, in
which case what you have would work fine.

Are you trying to avoid making too many changes to it?

**Comment by Puharesource** [comment]
I'll be doing a separate method of allowing for multiple headers / footers, while still allowing a single string as an answer as well, though that will happen after I've finished going over @Wundero latest PR.

**Comment by Wundero** [comment]
You could always try to have it filter through configuration sections that are titles, with names and such, and generate them, while having a global value for fallback if needed.
ex:
welcome_message:
  enabled: true
  fadeIn: 20
  fadeOut: 20
  stay: 40
  messages:
    one:
      title: 'Kay'
      subtitle: 'Yay'
    two:
      title: 'Bay'
      subtitle: 'Ray'
      fadeIn: 30
    three:
      title: 'Hoorah'
      subtitle: ''
      stay: 200

... and so on. You can choose to override timings this way as well, although that might be a bit confusing to set up. As well, with this method, you can also have any number of messages.

I was trying to avoid making changes to the rest of the system as I don't have my IDE setup for this repository and github doesn't tell you what goes wrong when you change something, and since this is not my plugin, I don't know where to look :3. 

One last thing, is there anything else you wanted to work on but haven't had the chance to, Puharesource? (Other than javascript because I don't know that language :P) If there is, I could try to write an implementation to save you some time.

**Comment by Puharesource** [comment]
There isn't really anything I can think off at the moment.

Btw, I do think you should try to setup the project with your IDE, since it'll speed up your process + then I won't have to fix silly mistakes that you have overseen xD
