### ISSUE TITLE
High mysql load when using {BALANCE} variable

### ISSUE THREAD

**Issue by EvilOlaf** [Puharesource/TitleManager#64]
Hey there,

I recently discovered that using the `{BALANCE}` variable at the player list causes high mysql load.

Usually my mysqld runs at about 0.3 to 1.0 % CPU load. When adding `{BALANCE}` to the player list the load raises to about 50 to 70 % CPU load. Removing the variable and reloading the config let the load drop immediately.

Also noticed that I receive error messages:
`The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
[09:48:40] [pool-42-thread-1/INFO]: [iConomy] Database Error: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure`

This is probably not be caused by TitleManager at all, more an problem with the MySQLd but it would be nice to know anyways how many queries this particular variable causes per second per player.

Spigot 1.8.8
iConomy "7.0" (obviously, I know it is outdated, but worked for me for years now ;))
Vault 1.5.6
TM1.5.11

I also ran a strace at the mysqld process and noticed that with `{BALANCE}` activated there was VERY high activity while there was almost none with  `{BALANCE}` disabled. I could find perfect matches when entering the `/money` command and see the output at strace. At the test I had about 10 players online and it is weird that these players cause so many queries.

Thanks for reading.

Best regards
Olaf

**Comment by Puharesource** [comment]
As far as I know, the only economy plugin that causes this type of issue, is iConomy, this is due to the fact that iConomy doesn't seem to cache any of the data that it receives from the MySQL database.

The amount of time the variable is refreshed depends on a number of things.
Let's say you've got the following scenario:

You've got 10 players online, no animation in the tabmenu, just the {BALANCE} variable.
This will make the tabmenu update 2 times a second * the amount of players online. `2 * 10 = 20` in that case, it updates 20 times a second, this is usually not an issue, however, in the case of iConomy, it is due to the fact it has to query the database every time TitleManager requests data from Vault.

I COULD cache the data myself, however, I feel like that should already be done by iConomy (even though it's very much so outdated).

**Comment by EvilOlaf** [comment]
Actually MySQL as it is should not care about 20 or 30 or even 100 queries per second, even if there was no config optimisation of the mySQLd at all. Also MySQL caches common queries by itself and their buffers are big enough to fit the database hundred times in it.

Anyway for some reason there is this very high cpu usage and I could not figure out why yet.

**Comment by Puharesource** [comment]
I am aware of that, however, in that case the only conclusion I can come up with is the fact that iConomy is doing something wrong, which sounds a bit strange to me.

TitleManager uses a separate thread when converting the variables / sending the messages, so unless your processor is extremely bad at multi-threading (which shouldn't even make a difference in the first place as this should be such a small task), I can't really see why it would cause a high cpu usage.

**Comment by EvilOlaf** [comment]
Ya, I also think it is an iConomy related issue for some reason. Guess I have to do some further debugging at the SQL side.
Thanks for your input.

**Comment by EvilOlaf** [comment]
Small push as I remembered that editing  an existing comment does not create a notification to the members of a repository. If you already read the additional text forgive me :)

**Comment by Puharesource** [comment]
That's true

Every time I call [this](https://github.com/MilkBowl/Vault/blob/master/src/net/milkbowl/vault/economy/plugins/Economy_iConomy6.java#L127) function in vault, it calls [this](https://github.com/iConomy/Core/blob/iConomy6/src/com/iCo6/system/Queried.java#L324) function, which queries the database.

Also just as a heads up, it seems like it's using usernames as the key it's checking data for rather than UUID's so if one of your players changes their names, they won't have any money left.

**Comment by EvilOlaf** [comment]
Ya I noticed the lack of UUID support at iConomy. Unfortunately first attempts to convert to another economy plugin like CraftConomy failed at the conversion process. The author also did not respond yet.

But that's another story ;).


If you plan to add some kind a caching for the economy feel free to do so, otherwise you may just close the issue report :).


Best regards
Olaf

**Comment by Puharesource** [comment]
Sorry, but it feels a little silly adding caching for a single economy plugin that has been abandoned for a long time.

Good luck finding a solution that'll work :).
