### ISSUE TITLE
Problem with ping.

### ISSUE THREAD

**Issue by FreeKillGR** [Puharesource/TitleManager#83]
http://prnt.sc/bp1uyv

Anyone know what is causing this.

**Comment by Puharesource** [comment]
The ping is calculated by the Minecraft server itself, I have however seen issues with VanishNoPacket, which might or might not cause the ping to be either very high or very low.

**Comment by T1MOXA** [comment]
The same problem...

**Comment by Puharesource** [comment]
@T1MOXA Like I told FreeKillGR, this cannot be fixed. It's all being calculated by the server and if the server isn't calculating it correctly, then there's nothing I can do.

**Comment by T1MOXA** [comment]
Maybe add a delay before transmitting data to the player or something else ?

**Comment by Puharesource** [comment]
That still won't change the ping, I might add a delay of x amount of seconds, but what if the ping is still fucked up after that amount of wait time? Another possibility would be to check if the ping is either over x MS or below 0, but that still won't be reliable, it would just look strange if it said ` MS` instead of `x MS`.

Not filtering the result from the ping, is the option in my opinion.

**Comment by T1MOXA** [comment]
I would be glad if you corrected :) 
When the players notice - begin to ask questions...

**Comment by Wundero** [comment]
The plugin has no say in what the number is; the number is calculated by Spigot's internals. There is no good way to fix this on this side, due to the nature of the game itself. The only real way of fixing this would be to guess what the ping is, but that is not a good solution to the problem as it is just as wrong as a large or negative number, but not as noticeable. Realistically this is a minor issue, but if you want it fixed you need to contact the devs of Spigot.
